# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.0.12
_src_path: git+https://github.com/akretion/akretion-addons-repo-template
black_version: 20.8b1
generate_requirements_txt: true
odoo_version: '14.0'
prettify_xml: true
python_line_length: 88
repo_slug: pos-sale-order
